BD/Pages/Add.cshtml.cs
using BD.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BD.Pages
{
	[Authorize]
	[IgnoreAntiforgeryToken]
	public class AddModel : PageModel
	{
		private readonly ApplicationContext context;
		public List<string> Message { get; set; } = new();
		public List<Material> Materials { get; private set; } = new();
		public List<Manufacturer> Manufacturers { get; private set; } = new();
		public List<Models.Type> Types { get; private set; } = new();
		public List<Country> Country { get; private set; } = new();
		public List<Details> Details { get; private set; } = new();
		[BindProperty]
		public Details Detail { get; set; } = new();
		//public Country Countries { get; private set; } = new();
		public AddModel(ApplicationContext db)
		{
			context = db;
		}

		public async Task OnGetAsync()
		{
			/*Details = await context.Details
				.Include(x => x.Country)
				.Include(x => x.Manufacturer)
				.Include(x => x.Material)
				.Include(x => x.Part_type)
				.OrderBy(x => x.Id)
				.ToListAsync();*/

			Materials = await context.Materials.OrderBy(m => m.Name).ToListAsync();
			Manufacturers = await context.Manufacturers.OrderBy(m => m.Name).ToListAsync();
			Types = await context.Types.OrderBy(t => t.Name).ToListAsync();
			Country = await context.Countries.OrderBy(c => c.Name).ToListAsync();
		}

		public async Task<IActionResult> OnPostAsync()
		{
			/*Details = await context.Details
				.Include(x => x.Country)
				.Include(x => x.Manufacturer)
				.Include(x => x.Material)
				.Include(x => x.Part_type)
				.OrderBy (x => x.Id)
				.ToListAsync();*/

			Materials = await context.Materials.OrderBy(m=>m.Name).ToListAsync();
			Manufacturers = await context.Manufacturers.OrderBy(m=>m.Name).ToListAsync();
			Types = await context.Types.OrderBy(t => t.Name).ToListAsync();
			Country = await context.Countries.OrderBy(c => c.Name).ToListAsync();


			if (Detail.Operating_voltage < 0 || Detail.Capacity < 0 || Detail.Power < 0 || Detail.Resistance < 0 || Detail.Electric_current < 0 || Detail.Inductance < 0 || Detail.Price < 0)
			{
				if (Message.Count > 0)
				{
					Message.RemoveAt(0);
				}
				Message.Add("Incorrect data!");
				return Page();
			}
			else if (Detail.MinOperating_Temp > Detail.MaxOperating_Temp)
			{
				if (Message.Count  > 0) 
				{ 
					Message.RemoveAt(0);
				}
				Message.Add("Incorrect min/max temperature values ​​entered!");
				return Page();	
			}
			
			else
			{
				if (Message.Count > 0)
				{
					Message.RemoveAt(0);
				}
				Message.Add("Part added successfully!");
				context.Details.Add(Detail);
				await context.SaveChangesAsync();
				return Page();
			}

		}

	}
}

BD/Pages/AddManufacturer.cshtml.cs
using BD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BD.Pages
{
	[IgnoreAntiforgeryToken]
	public class AddManufacturerModel : PageModel
	{
		private readonly ApplicationContext context;
		public List<string> Message { get; set; } = new();
		public List<Manufacturer> Manufacturers { get; set; } = new();
		public List<Country> Countries { get; set; } = new();
		[BindProperty]
		public Manufacturer Manufacturer { get; set; } = new();
		public AddManufacturerModel(ApplicationContext db)
		{
			context = db;
		}

		public void OnGet()
		{
			Manufacturers = context.Manufacturers.AsNoTracking().ToList();
			Countries = context.Countries.OrderBy(c=>c.Name).ToList();
		}

		public async Task<IActionResult> OnPostAsync(string Name)
		{
			Manufacturers = await context.Manufacturers.AsNoTracking().ToListAsync();
			Countries = await context.Countries.OrderBy(c => c.Name).ToListAsync();
			var manufacturer = Manufacturers.FindAll(m=>m.Name == Name);
			Message.Clear();
			if (manufacturer.Count == 0)
			{
				Message.Add("Manufacturer added!");
				context.Manufacturers.Add(Manufacturer);
				await context.SaveChangesAsync();
				return Page();
			}
			else
			{
				Message.Add("The manufacturer is already in the database!");
				return Page();
				
			}
		}
	}
}

BD/Pages/AddMaterial.cshtml.cs
using BD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BD.Pages
{
	[IgnoreAntiforgeryToken]
	public class AddMaterialModel : PageModel
	{
		private readonly ApplicationContext context;
		public List<string> Message = new();
		public List<Material> Materials { get; set; } = new();

		[BindProperty]
		public Material Material { get; set; } = new();

		public AddMaterialModel(ApplicationContext db)
		{
			context = db;
		}

		public void OnGet()
		{
			Materials = context.Materials.AsNoTracking().ToList();
		}

		public async Task<IActionResult> OnPostAsync(string Name)
		{
			Materials = context.Materials.AsNoTracking().ToList();
			var material = Materials.Find(m=>m.Name == Name);
			Message.Clear();
			if (material == null)
			{
				Message.Add("Material added!");
				context.Materials.Add(Material);
				await context.SaveChangesAsync();
				
				return Page();
			}
			else
			{
				
				Message.Add("The material is already in the database!");
				return Page();
				
			}
			
		}


	}
}

BD/Pages/Capacitors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class CapacitorsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/Diodes.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class DiodesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
	public class IndexModel : PageModel
	{
		public void OnGet()
		{
		}
	}
}

BD/Pages/Inductors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class InductorsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/IntegratedCircuits.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class IntegratedCircuitsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToPage("Index");
            }
            return Page();
        }
    }
}

BD/Pages/Microcontrollers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class MicrocontrollersModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/Resistors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class ResistorsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/Search.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class SearchModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/SearchOne.cshtml.cs
using BD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BD.Pages
{
	[IgnoreAntiforgeryToken]
	public class SearchOneModel : PageModel
	{
		private readonly ApplicationContext context;
		public List<Details> Details { get; set; } = new();
		public List<Details> DetailSearch { get; set; } = new();
		public List<Country> Countries { get; set; } = new();
		public List<Manufacturer> Manufacturers { get; set; } = new();
		public List<string> Names { get; set; } = new();
		public int ManId = 0;

		public SearchOneModel(ApplicationContext db)
		{
			context = db;

		}


		public async Task OnGetAsync()
		{
			Details = await context.Details
			   .Include(x => x.Country)
			   .Include(x => x.Manufacturer)
			   .Include(x => x.Material)
			   .Include(x => x.Part_type)
			   .ToListAsync();
			Countries = Details.Select(x => x.Country).Distinct().OrderBy(c=>c.Name).ToList();
			Manufacturers = Details.Select(x => x.Manufacturer).Distinct().OrderBy(m=>m.Name).ToList();	
		}

		public async Task OnPostOne(int CountryId)
		{
			Details = await context.Details
			   .Include(x => x.Country)
			   .Include(x => x.Manufacturer)
			   .Include(x => x.Material)
			   .Include(x => x.Part_type)
			   .ToListAsync();
			Countries = Details.Select(x => x.Country).Distinct().OrderBy(c => c.Name).ToList();
			Manufacturers = Details.Select(x => x.Manufacturer).Distinct().OrderBy(m => m.Name).ToList();

			DetailSearch = Details.FindAll(d => d.Country.Id == CountryId);
			
		}

		public async Task OnPostFirst(int ManufacturerId)
		{
			ManId = ManufacturerId;
			Details = await context.Details
			   .Include(x => x.Country)
			   .Include(x => x.Manufacturer)
			   .Include(x => x.Material)
			   .Include(x => x.Part_type)
			   .ToListAsync();
			Countries = Details.Select(x => x.Country).Distinct().OrderBy(c => c.Name).ToList();
			Manufacturers = Details.Select(x => x.Manufacturer).Distinct().OrderBy(m => m.Name).ToList();

	
			DetailSearch = Details.FindAll(d => d.ManufacturerId == ManufacturerId);
			
			Names = DetailSearch.Select(x=>x.Name).Distinct().ToList();
		}

		public async Task OnPostSecond(int NameId, string Name)
		{
			

			Details = await context.Details
			   .Include(x => x.Country)
			   .Include(x => x.Manufacturer)
			   .Include(x => x.Material)
			   .Include(x => x.Part_type)
			   .ToListAsync();
			Countries = Details.Select(x => x.Country).Distinct().OrderBy(c => c.Name).ToList();
			Manufacturers = Details.Select(x => x.Manufacturer).Distinct().OrderBy(m => m.Name).ToList();

			DetailSearch = Details.FindAll(d => (d.Name == Name) && (d.ManufacturerId == NameId));
			
			Names = DetailSearch.Select(x => x.Name).Distinct().ToList();

		}
	}
}

BD/Pages/SearchTwo.cshtml.cs
using BD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BD.Pages
{
	[IgnoreAntiforgeryToken]
	public class SearchTwoModel : PageModel
	{
		private readonly ApplicationContext context;

		public List<Details> Details { get; set; } = new();

		public List<Details> DetailSearch { get; set; } = new();

		public List<Details> AllDetailSearch { get; set; } = new();

		//public List<Country> Countries { get; set; } = new();
		public List<Manufacturer> Manufacturers { get; set; } = new();

		public List<string> Names { get; set; } = new();

		public int ManId = 0;

		public SearchTwoModel(ApplicationContext db)
		{
			context = db;

		}


		public async Task OnGetAsync()
		{
			Details = await context.Details
			   .Include(x => x.Country)
			   .Include(x => x.Manufacturer)
			   .Include(x => x.Material)
			   .Include(x => x.Part_type)
			   .ToListAsync();
			//Countries = Details.Select(x => x.Country).Distinct().OrderBy(c => c.Name).ToList();
			Manufacturers = Details.Select(x => x.Manufacturer).Distinct().OrderBy(m => m.Name).ToList();
		}

		public async Task OnPostFirst(int ManufacturerId)
		{
			ManId = ManufacturerId;
			Details = await context.Details
			   .Include(x => x.Country)
			   .Include(x => x.Manufacturer)
			   .Include(x => x.Material)
			   .Include(x => x.Part_type)
			   .ToListAsync();
			//Countries = Details.Select(x => x.Country).Distinct().OrderBy(c => c.Name).ToList();
			Manufacturers = Details.Select(x => x.Manufacturer).Distinct().OrderBy(m => m.Name).ToList();


			DetailSearch = Details.FindAll(d => d.ManufacturerId == ManufacturerId).OrderBy(m => m.Name).ToList();

			Names = DetailSearch.Select(x => x.Name).Distinct().ToList();
		}

		public async Task OnPostSecond(int NameId, string Name)
		{
			ManId = NameId;

			Details = await context.Details
			   .Include(x => x.Country)
			   .Include(x => x.Manufacturer)
			   .Include(x => x.Material)
			   .Include(x => x.Part_type)
			   .ToListAsync();
			//Countries = Details.Select(x => x.Country).Distinct().OrderBy(c => c.Name).ToList();
			Manufacturers = Details.Select(x => x.Manufacturer).Distinct().OrderBy(m => m.Name).ToList();

			AllDetailSearch = Details.FindAll(d => d.ManufacturerId == NameId).OrderBy(m => m.Name).ToList();

			DetailSearch = Details.FindAll(d => (d.Name == Name) && (d.ManufacturerId == NameId));

			Names = AllDetailSearch.Select(x => x.Name).Distinct().ToList();

		}
	}
}

BD/Pages/Sensors.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class SensorsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/Statistic.cshtml.cs
using BD.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
	[IgnoreAntiforgeryToken]
	public class StatisticModel : PageModel
    {
        private readonly ApplicationContext context;
		public int CountMat;
        public List<Material> Materials { get; set; } = new();
		public List<Details> Details { get; set; } = new();
		public List<Models.Type> Types { get; set; } = new();
		public List<Manufacturer> Manufacturers { get; set; } = new();
		public StatisticModel(ApplicationContext db)
		{
			context = db;

		}
		public void OnGet()
        {
			Materials = context.Materials.ToList();
								
			Details = context.Details.ToList();
			Types = context.Types.ToList();	
			Manufacturers = context.Manufacturers.ToList();
		}
    }
}

BD/Pages/Transformers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BD.Pages
{
    public class TransformersModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BD/Pages/AddManufacturer.cshtml
@page
@model BD.Pages.AddManufacturerModel
@{
	ViewBag.Title = "Добавление фирмы-изготовителя";
	Layout = "Shared/_Layout.cshtml";
}

@section Styles {
	<link rel="stylesheet" href="~/css/Add.css">
	
}

<body>
	<div class="add-page">
		<form method="post">
			<label>Фирма-изготовитель<input required name="Name" maxlength="30" id="NameMan"/></label><br />
			<label>Адрес фирмы<input name="Address" maxlength="50" id="Address"/></label><br />
				<label>
					Страна фирмы
					<select name="Country" id="CountryId">
				<option hidden selected disabled>Выберите страну</option>
				@foreach (var item in Model.Countries)
				{
							<option value="@item.Id">@item.Name</option>
						}
			</select></label><br />
			<label>Телефон<input type="tel" pattern="\+[0-9]{11}" name="Phone" placeholder="+78005553535" id="Phone"/></label><br />
			<label>ФИО директора фирмы<input name="Director" maxlength="80" id="Director"/></label><br />
			<label>Вид деятельности фирмы<input name="Activity" maxlength="30" id="Activity"/></label><br />
			<div class="button-container">
				<button onclick="DeleteItem1()">Добавить фирму</button>
				<input type="button" onclick="SaveForm(); window.location.href='Add';" value="Назад" />
			</div>
		</form>
		@if (Model.Message.Count != 0)
		{
			<p>@Model.Message[0]</p>
		}
		
		
	</div>
<!--<table>
		<tr><th>ИД</th><th>Название</th></tr>
		@foreach(var Manufacturer in Model.Manufacturers)
		{
			<tr>
				<td>@Manufacturer.Id</td>
				<td>@Manufacturer.Name</td>
			</tr>
		}
		</table>-->

	<script>
		if (sessionStorage.getItem("NameMan") !== null) {
			document.getElementById("NameMan").value = sessionStorage.getItem("NameMan");
		}
		if (sessionStorage.getItem("Address") !== null) {
			document.getElementById("Address").value = sessionStorage.getItem("Address");
		}
		if (sessionStorage.getItem("CountryId") !== null) {
			document.getElementById("CountryId").value = sessionStorage.getItem("CountryId");
		}
		if (sessionStorage.getItem("Phone") !== null) {
			document.getElementById("Phone").value = sessionStorage.getItem("Phone");
		}
		if (sessionStorage.getItem("Director") !== null) {
			document.getElementById("Director").value = sessionStorage.getItem("Director");
		}
		if (sessionStorage.getItem("Activity") !== null) {
			document.getElementById("Activity").value = sessionStorage.getItem("Activity");
		}

		function SaveForm() {
			let Name = document.getElementById("NameMan").value;
			sessionStorage.setItem("NameMan", Name);
			let Address = document.getElementById("Address").value;
			sessionStorage.setItem("Address", Address);
			let Country = document.getElementById("CountryId").value;
			sessionStorage.setItem("CountryId", Country);
			let Phone = document.getElementById("Phone").value;
			sessionStorage.setItem("Phone", Phone);
			let Director = document.getElementById("Director").value;
			sessionStorage.setItem("Director", Director);
			let Activity = document.getElementById("Activity").value;
			sessionStorage.setItem("Activity", Activity);
		}

		function DeleteItem1() {
			sessionStorage.removeItem("NameMan");
			sessionStorage.removeItem("Address");
			sessionStorage.removeItem("CountryId");
			sessionStorage.removeItem("Phone");
			sessionStorage.removeItem("Director");
			sessionStorage.removeItem("Activity");
		}
	</script>
</body>

BD/Pages/Capacitors.cshtml
@page
@model BD.Pages.CapacitorsModel
@{
    ViewBag.Title = "Конденсаторы";
    Layout = "Shared/_Layout.cshtml";
}

<body>
    <h2>Что такое конденсаторы?</h2>
    <p>Конденсаторы - это электронные компоненты, которые накапливают электрический заряд и могут использоваться для фильтрации, сглаживания и временной задержки сигналов.</p>

    <h2>Типы конденсаторов</h2>
    <ul>
        <li><strong>Электролитические</strong>: имеют большую емкость, используются в источниках питания.</li>
        <li><strong>Керамические</strong>: обладают малой емкостью и используются в фильтрах.</li>
        <li><strong>Танталовые</strong>: стабильные и надежные, часто применяются в мобильных устройствах.</li>
        <li><strong>Микросхемные</strong>: используются в интегральных схемах.</li>
    </ul>

    <h2>Таблица характеристик конденсаторов</h2>
    <table>
        <tr>
            <th>Тип конденсатора</th>
            <th>Емкость (μF)</th>
            <th>Напряжение (V)</th>
        </tr>
        <tr>
            <td>Электролитический</td>
            <td>10</td>
            <td>25</td>
        </tr>
        <tr>
            <td>Керамический</td>
            <td>1</td>
            <td>50</td>
        </tr>
        <tr>
            <td>Танталовый</td>
            <td>100</td>
            <td>16</td>
        </tr>
    </table>

    <h2>Применение конденсаторов</h2>
    <p>Конденсаторы используются в различных электронных устройствах, включая блоки питания, аудиоаппаратуру и радиоприемники.</p>
</body>

BD/Pages/Index.cshtml
@page
@model BD.Pages.IndexModel
@{
	ViewBag.Title = "Главная";
	Layout = "Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/css/Index.css">

}

    <div class="content">
        <h1 class="welcome">Добро пожаловать на сайт "Электронные компоненты"</h1>
        <p class="info">Наш сайт предоставляет информацию о различных радиодеталях, их характеристиках и применении. Здесь вы можете легко найти нужные компоненты для ваших проектов и получать актуальные сведения.</p>
    </div>

BD/Pages/SearchOne.cshtml
@page
@model BD.Pages.SearchOneModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewBag.Title = "Поиск по одному атрибуту";
    Layout = "Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/css/SearchOne&Two.css">
}

<body>
    <div class="search-page">
        <form method="post" asp-page-handler="One" id="One">
            <div class="search-form">
                <label>Страна производства:</label>
                <select required name="CountryId" id="Country">
                    <option selected value="@Model.Countries[0].Id">@Model.Countries[0].Name</option>
                    @foreach (var item in Model.Countries.Skip(1))
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
                <button onclick="SaveForm()">Поиск</button>
            </div>
        </form>

        <div class="search-results">
            @if (Model.DetailSearch.Count != 0)
            {
                <table>
                    <thead>
                        <tr>
                            <th>Название</th>
                            <th>Цена, руб.</th>
                            <th>Страна изготовления</th>
                            <th>Тип</th>
                            <th>Модель</th>
                            <th>Рабочее напряжение, В</th>
                            <th>Мин. раб. темп., С</th>
                            <th>Макс. раб. темп., С</th>
                            <th>Ёмкость, нФ</th>
                            <th>Мощность, Вт</th>
                            <th>Сопротивление, Ом</th>
                            <th>Сила тока, А</th>
                            <th>Индуктивность, мГн</th>
                            <th>Материал</th>
                            <th>Производитель</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.DetailSearch)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.Price</td>
                                <td>@item.Country.Name</td>
                                <td>@item.Part_type.Name</td>
                                <td>@item.Model</td>
                                <td>@item.Operating_voltage</td>
                                <td>@item.MinOperating_Temp</td>
                                <td>@item.MaxOperating_Temp</td>
                                <td>@item.Capacity</td>
                                <td>@item.Power</td>
                                <td>@item.Resistance</td>
                                <td>@item.Electric_current</td>
                                <td>@item.Inductance</td>
                                <td>@item.Material.Name</td>
                                <td>@item.Manufacturer.Name</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>

    <script>
        if (sessionStorage.getItem("Country") !== null) {
            document.getElementById("Country").value = sessionStorage.getItem("Country");
        }

        function SaveForm() {
            let Country = document.getElementById("Country").value;
            sessionStorage.setItem("Country", Country);
        }

        function DeleteItem() {
            sessionStorage.removeItem("Country");
            console.log(345);
        }
    </script>
</body>

BD/Pages/SearchTwo.cshtml
@page
@model BD.Pages.SearchTwoModel;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
	ViewBag.Title = "Поиск";
	Layout = "Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/css/SearchOne&Two.css">
}

<body>
    <div class="search-page">
        
        <form id="First" method="post" asp-page-handler="First">
            <div class="search-form">
                <label>Изготовитель:</label>
                <select onchange="document.getElementById('First').submit(); SaveForm();" required name="ManufacturerId" id="Manufacturer">
                    <option selected hidden disabled>Выберите производителя</option>
                    @foreach (var item in Model.Manufacturers)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </div>
        </form>
        
        <form id="Second" method="post" asp-page-handler="Second">
            <input type="hidden" name="NameId" value="@Model.ManId" id="DetailId" />
            <div class="search-form">
                <label>Название детали:</label>
                <select onchange="SaveForm(); " required name="Name" id="Detail">
                    @foreach (var item in Model.Names)
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <button onclick="SaveForm();">Поиск</button>

            </div>
        </form>
            
        

        <div class="search-results">
            @if (Model.DetailSearch.Count != 0)
            {
                <table>
                    <thead>
                        <tr>
                            <th>Название</th>
                            <th>Цена, руб.</th>
                            <th>Страна изготовления</th>
                            <th>Тип</th>
                            <th>Модель</th>
                            <th>Рабочее напряжение, В</th>
                            <th>Мин. раб. темп., С</th>
                            <th>Макс. раб. темп., С</th>
                            <th>Ёмкость, нФ</th>
                            <th>Мощность, Вт</th>
                            <th>Сопротивление, Ом</th>
                            <th>Сила тока, А</th>
                            <th>Индуктивность, мГн</th>
                            <th>Материал</th>
                            <th>Производитель</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.DetailSearch)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.Price</td>
                                <td>@item.Country.Name</td>
                                <td>@item.Part_type.Name</td>
                                <td>@item.Model</td>
                                <td>@item.Operating_voltage</td>
                                <td>@item.MinOperating_Temp</td>
                                <td>@item.MaxOperating_Temp</td>
                                <td>@item.Capacity</td>
                                <td>@item.Power</td>
                                <td>@item.Resistance</td>
                                <td>@item.Electric_current</td>
                                <td>@item.Inductance</td>
                                <td>@item.Material.Name</td>
                                <td>@item.Manufacturer.Name</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>

	<script>
		if (sessionStorage.getItem("Manufacturer") !== null) {
			document.getElementById("Manufacturer").value = sessionStorage.getItem("Manufacturer");
		}
		if (sessionStorage.getItem("Detail") !== null) {
			document.getElementById("Detail").value = sessionStorage.getItem("Detail");
		}

		function SaveForm() {
			let Manufacturer = document.getElementById("Manufacturer").value;
			sessionStorage.setItem("Manufacturer", Manufacturer);
			let Detail = document.getElementById("Detail").value;
			sessionStorage.setItem("Detail", Detail);
		}

		function DeleteItem() {

			sessionStorage.removeItem("Manufacturer");
			sessionStorageremoveItem("Detail");
			console.log(345);
		}
	</script>
</body>